name: Build infrastructure
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #CI
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Verify Azure Login
      run: az account show
    - name: Set Terraform Version
      run: echo "TERRAFORM_VERSION=1.5.7" >> $GITHUB_ENV
    - name: Install Terraform
      run: |
        curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin/
    - name: Verify Terraform
      run: terraform version
    - name: Terraform Init
      run: terraform -chdir=terraform init
    - name: Terraform Plan
      run: terraform -chdir=terraform plan
    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
    - name: Deploy Kubernetes Resources
      run: |
        az aks get-credentials  --resource-group cv.bach --name aks-devops-project --overwrite-existing
        kubectl apply -f kubernetes/configmap.yaml
        kubectl apply -f kubernetes/secret.yaml
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/service.yaml

